#!/usr/bin/env zsh
echo $PWD
echo $USER

mv $HOME/.zshrc $HOME/.zshrc.bak
# mv $HOME/.zsh_profile $HOME/.zsh_profile.bak
rm $HOME/.zshrc 


if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="bin,tmux,uwuntu,zsh"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.dotfiles
fi
STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install