#!/usr/bin/env bash
# alias asdf="setxkbmap real-prog-dvorak"
# alias aoeu="setxkbmap us"
# alias lkj="setxkbmap real-prog-dvorak"
# alias snth="setxkbmap us"
alias xsc="xclip -selection clipboard"

alias q='exit'
alias c='clear'
alias h='history'
alias cs='clear;ls'
alias p='cat'
alias pd='pwd'
alias lsa='ls -a'
alias lsl='ls -l'
alias pd='pwd'
alias t='time'
alias k='kill'
alias null='/dev/null'
alias home='cd ~'
alias root='cd /'
alias o=open
alias ..='cd ..'
alias ...='cd ..; cd ..'
alias ....='cd ..; cd ..; cd ..'
alias python='python3'
alias pip='pip3'
# Shortcuts to vimrc and bashrc
alias vimrc='nvim ~/.vimrc'
alias bashrc='nvim ~/.bashrc'
alias loadbash='source ~/.bashrc'

#!/usr/bin/env bash
# alias esc="$HOME/.config/sway/config"
alias vim="$VIM"
alias vims="NVIM_LISTEN_ADDRESS=/tmp/nvim $VIM"
# alias kill_netflix="pkill -9 GIBBON_MAIN"
alias work="cd ~/work"

alias python="python3"
alias cbp="cat $DOTFILES/zsh/.config/.zsh_profile"
alias ebp="$VIM $DOTFILES/.zsh_profile"
# alias etc="$VIM $DOTFILES/awesome-streamerrc/ThePrimeagen/.tmux.conf"
alias bp="dotFileInstall && source ~/.zshrc"
# alias evrc="$VIM $DOTFILES/awesome-streamerrc/ThePrimeagen/.vimrc"
# alias enrc="nvim $DOTFILES/awesome-streamerrc/ThePrimeagen/init.vim --cmd \"cd $DOTFILES/awesome-streamerrc/ThePrimeagen/init.vim\""
alias yolo="git push origin master --force --no-verify"
# alias eirc="nvim $XDG_CONFIG_HOME/i3/i3config"
alias cvrc="cat $DOTFILES/vimrc/.vimrc"
alias dotFileInstall="$DOTFILES/install"

alias pjson="python -mjson.tool"
alias killBT="rfkill block bluetooth"
alias unKillBT="rfkill unblock bluetooth"
alias cclip="xclip -selection clipboard"
alias pclip="xclip -selection clipboard"
# alias timeplus="~/dotfiles/apps/time_plus_30"
# alias echotime="~/dotfiles/apps/echo_time"
alias livestream_screenkey="screenkey -s large --scr 2 -p bottom --geometry 1210x300+712+810";
alias yt_screenkey="screenkey -s large --scr 1 -p bottom --geometry 510x300+1412+850";

alias cnpm="cat ~/.npmrc"
alias pnpm='rm ~/.npmrc'